### ISSUE TITLE
Is it possible to support MinGW to include libmusicxml.rc?

### ISSUE THREAD

**Issue by school510587** [grame-cncm/libmusicxml#14]
Currently, libmusicxml.rc is excluded from MinGW build process.

if(MSVC)
	enable_language(RC)
	set(LIBCONTENT ${CORESRC} ${COREH} ${LXML}/win32/libmusicxml/libmusicxml.rc)
else()

I tried to remove this if...else...endif condition so that windres tool of MinGW was used to compile libmusicxml.rc.
However, I got errors from the following lines:

 FILEVERSION 3.1,1,0
 PRODUCTVERSION 3.1,1,0

Problems disappeared after changing them into:

 FILEVERSION 3,1,1,0
 PRODUCTVERSION 3,1,1,0

Both 3.1 and 3,1 are accepted by MSVC, but only 3,1 is accepted by windres (MinGW).
Thus, did I miss anything to let windres accept 3.1,1,0? Or, would you change libmusicxml.rc to enable MinGW to compile it? Thanks!

**Comment by dfober** [comment]
> Le 23 mars 2017 à 22:07, school510587 <notifications@github.com> a écrit :
> 
> Currently, libmusicxml.rc is excluded from MinGW build process.
> 
> if(MSVC)
> enable_language(RC)
> set(LIBCONTENT ${CORESRC} ${COREH} ${LXML}/win32/libmusicxml/libmusicxml.rc)
> else()
> 
> I tried to remove this if...else...endif condition so that windres tool of MinGW was used to compile libmusicxml.rc.
> However, I got errors from the following lines:
> 
> FILEVERSION 3.1,1,0
> PRODUCTVERSION 3.1,1,0
> 
it was a typing error…
it’s fixed and pushed to github
—
Dom

**Comment by school510587** [comment]
libmusicxml.rc is fixed now, and I can build successfully. Could you remove the condition in CMakeLists.txt to allow MinGW to compile RC scripts? Thanks!

**Comment by dfober** [comment]
> Le 24 mars 2017 à 05:39, school510587 <notifications@github.com> a écrit :
> 
> libmusicxml.rc is fixed now, and I can build successfully. Could you remove the condition in CMakeLists.txt to allow MinGW to compile RC scripts? Thanks!

Can you make it on your side (I don’t know what is MinGW environment for cmake and I can’t test) and send me the modified CMakeLists (or via a pull request).

**Comment by school510587** [comment]
I just make this change: 

-if(MSVC)
+if(MSVC OR MINGW)
	enable_language(RC)

There must be other building environments on win32. However, I also only know MSVC and MINGW.
So, this modification solves my issue, but it is not for all possibilities.
If OK, please apply this change. Thanks!

Here are commands that I use, assuming MinGW compilers are already in PATH. The current directory is libmusicxml's root directory.
cmake build -G "MinGW Makefiles"
mingw32-make

**Comment by dfober** [comment]
that’s done and pushed to github

**Comment by school510587** [comment]
Fixed, thanks.
