### ISSUE TITLE
Make xml2lilypond's --help and --version options emit data to stdout

### ISSUE THREAD

**Issue by lemzwerg** [grame-cncm/libmusicxml#17]
On Unix platforms it is common that the output of `--help` and `--version` is sent to stdout.  Reason is that you then can easily pipe the output to a pager, e.g., `xml2lilypond --help | less`.

Currently, it is sent to stderr.

Additionally, for `--help`, the final message
```
---No arguments have been supplied, exiting. ---
```
should be suppressed.

**Comment by jacques-menu** [comment]
> Le 31 oct. 2017 à 14:22, lemzwerg <notifications@github.com> a écrit :
> 
> On Unix platforms it is common that the output of --help and --version is sent to stdout. Reason is that you then can easily pipe the output to a pager, e.g., xml2lilypond --help | less.
> 
> Currently, it is sent to stderr.
> 
> Additionally, for --help, the final message
> 
> ---No arguments have been supplied, exiting. ---
> should be suppressed.
> 
OK, I’ll do that and merge with you changes.

I’ve never done a git merge yet.vWhat are the difficulties that may arise?

The changes I made to the library are:
	- adding the input line number to xmlelement, crucial;
	- adding to rational, that should be no problem.

JM

**Comment by dfober** [comment]
> Le 31 oct. 2017 à 16:35, jacques-menu <notifications@github.com> a écrit :
> 
> > Le 31 oct. 2017 à 14:22, lemzwerg <notifications@github.com> a écrit :
> > 
> > On Unix platforms it is common that the output of --help and --version is sent to stdout. Reason is that you then can easily pipe the output to a pager, e.g., xml2lilypond --help | less.
> > 
> > Currently, it is sent to stderr.
> > 
> > Additionally, for --help, the final message
> > 
> > ---No arguments have been supplied, exiting. ---
> > should be suppressed.
> > 
> OK, I’ll do that and merge with you changes.
> 
> I’ve never done a git merge yet.vWhat are the difficulties that may arise?

you don’t have to merge for changes on your branch. Just make a 
> git pull
to update your local repository.

**Comment by dfober** [comment]
@jacques-menu  can we close this issue ? (I guess yes)

**Comment by jacques-menu** [comment]
> Le 27 mai 2020 à 21:04, Dominique Fober <notifications@github.com> a écrit :
> @jacques-menu <https://github.com/jacques-menu> can we close this issue ? (I guess yes)
> 
Yes, we can!

JM
