### ISSUE TITLE
Could you please make releases more frequently so that packages can use them instead of the current version?

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/libmusicxml#18]

**Comment by dfober** [comment]
I'm currently working on that. A new release should be available by the end of the year.

**Comment by jacques-menu** [comment]
2.2 ou 3.0?

JM

**Comment by yurivict** [comment]
You also need to make version numbers consistent.
Your commend says ```3.00```. GitHub tag says v300.
And:
```
$ git describe --tags 707085e 
v300-159-g707085e8
```

So the version is actually 300, not 3.00.

**Comment by dfober** [comment]
That's fixed. The tag has been renamed more consistently to v3.00. You'll have to update your repository if you have a reference to v300.

**Comment by dvzrv** [comment]
what's the status on this? I might need to package this for csound.

**Comment by jacques-menu** [comment]
Hello David,

Dominique Fober, who is in charge of libmusicxml2, is a bit busy these days, this is thus my personal, non-authoritative answer.

This lib is very stable : I’m using it, working actively on the lilypond branch, that will be merged with the master as soon as I have an alpha1 version.

HTH!

--

Jacques Menu
mailto:imj-219@bluewin.ch

**Comment by dvzrv** [comment]
> This lib is very stable : I’m using it, working actively on the
> lilypond branch, that will be merged with the master as soon as I have
> an alpha1 version.
Thanks! Enough for me ;-)
