### ISSUE TITLE
Add -std=c++11 on generating MinGW Makefiles

### ISSUE THREAD

**Issue by school510587** [grame-cncm/libmusicxml#19]
The current dev branch fails to compile using MinGW g++ 4.9 series. Specifically, I compiled it using MinGW g++ 4.9.4.
After adding the following lines into CMakeLists.txt, it will work:

@@ -54,6 +54,8 @@ elseif(WIN32)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;add_definitions(-DVC6)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elseif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 8 2005")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;add_definitions(-DVC2005)
&plus;&nbsp;&nbsp;&nbsp;&nbsp;elseif(${CMAKE_GENERATOR} STREQUAL "MinGW Makefiles")
&plus;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;endif(${CMAKE_GENERATOR} STREQUAL "Visual Studio 6")

Could you help add them? Thanks.

**Comment by dfober** [comment]
covered by cmake config
