### ISSUE TITLE
Please update SONAME when you change te library interface

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/libmusicxml#23]
Between versions ```3.11``` and ```3.13``` you changed the interface, ex. added ```virtual``` to ```guidoelement```, but left SONAME to be ```libmusicxml2.so.3```. This is error-prone, because SONAME is what drives updates of dependencies. In case of ```3.13``` dependencies need to be rebuilt, but SONAME didn't change which means that dependencies don't need to be rebuilt.

**Comment by dfober** [comment]
I discover that there are other mistakes. I'll fix all that asap.

**Comment by dfober** [comment]
That's done (version numbers have also changed)
