### ISSUE TITLE
please don't delete and downgrade released versions

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/libmusicxml#24]
@dfober Please don't delete and force-downgrade an already released version!
I have pushed version 3.13 to Arch Linux' official repositories and you removed its sources and (decremented the version to 3.12). What's the reason behind that?
This breaks several things at the same time: semver, reproducible downstream packaging, trust.

Please only increment your version (even if you deem a version to be unstable or unusable, just make a new release with a higher version number!) in the future.

**Comment by dfober** [comment]
The release 3.13 was actually 3.12. That's why I've downgraded the version number and removed the corresponding tag. Sorry for the inconvenience. I won't do it again (promised!).

**Comment by dvzrv** [comment]
Thanks! 👍
