### ISSUE TITLE
How to generate the framework for iOS?

### ISSUE THREAD

**Issue by AliliWl** [grame-cncm/libmusicxml#30]
Check dependencies
warning: The armv7 architecture is deprecated for your deployment target (iOS 12.1). You should update your ARCHS build setting to remove the armv7 architecture.
warning: The armv7s architecture is deprecated for your deployment target (iOS 12.1). You should update your ARCHS build setting to remove the armv7s architecture.

PhaseScriptExecution CMake\ Rules ios/libmusicxml2.build/Release-iphoneos/ALL_BUILD.build/Script-7DF70B90500B41DB8E377C36.sh
    cd /Users/liwang/Desktop/libmusicxml-dev/build
    /bin/sh -c /Users/liwang/Desktop/libmusicxml-dev/build/ios/libmusicxml2.build/Release-iphoneos/ALL_BUILD.build/Script-7DF70B90500B41DB8E377C36.sh
echo ""

echo Build\ all\ projects
Build all projects

** BUILD SUCCEEDED **

cp ios/Release-iphoneos/libmusicxml2.a .

Why can't I call the API when I use it?

**Comment by dfober** [comment]
Regarding the armv7 and armv7s architectures, it's just a warning. Anyway, the compiler does its job and these architectures are well present in the archive.

> Why can't I call the API when I use it?

Could you give more details? What API are you calling? What's exactly the problem?

**Comment by AliliWl** [comment]
![image](https://user-images.githubusercontent.com/8400922/49501020-f0093a00-f8ac-11e8-8d9e-1c885ec368d1.png)

**Comment by arshiacont** [comment]
@AliliWl We use LibMusicXML on iOS with out an issue. 

From your screenshot, it seems like there is a problem with your iOS project where the Framework is not found and in return you don't see the headers.

**Comment by AliliWl** [comment]
In addition to copying the Framework into my project, do I need to make other settings?

**Comment by lihu3601456** [comment]
请问你这边弄好了吗，我也需要用到这个，但是不知道怎么弄

**Comment by dfober** [comment]
in a terminal, just type 
~~~~~~~~~~~~
$ cd your_libmusicxml_folder/build
$ make ios
~~~~~~~~~~~~
Have also a look at the [building instructions](https://github.com/grame-cncm/libmusicxml/wiki/Building)

**Comment by lihu3601456** [comment]
![屏幕快照 2019-10-30 下午3 58 49](https://user-images.githubusercontent.com/15259761/67839263-33f0d780-fb2e-11e9-8e7b-ce7de10fbb0f.png)
请问这个怎么处理

**Comment by arshiacont** [comment]
@lihu3601456 Your error has nothing to do with LibMusicXML. You are programming in ObjectiveC but you are using C++. Your project shouldn't be seeing the C++ file if you prepare it correctly. Look on the web on how to integrate Frameworks into an XCode project.

**Comment by lihu3601456** [comment]
![屏幕快照 2019-10-30 下午5 10 49](https://user-images.githubusercontent.com/15259761/67844469-bd0d0c00-fb38-11e9-96d0-50365137dd86.png)
还是会有错
