### ISSUE TITLE
Visibility issue in lilypond/utilities.h

### ISSUE THREAD

**Issue by school510587** [grame-cncm/libmusicxml#32]
I failed to build xml2ly.exe, because the linker could not find std::ostream& operator<< (std::ostream&, const indenter&).
This is an issue of visibility. Could you add EXP before its declaration in utilities.h?
Also, std::ostream& operator<< (std::ostream&, const timing&) is not declared EXP. If this operator is sure to be part of the API, please add EXP, too.
Thanks.

**Comment by dfober** [comment]
could you give more details? the target platform, your compiler.
I’m just a bit surprised because compilation is automatically checked with travis on linux and appveyor on windows.

**Comment by school510587** [comment]
In the 2nd case, I can reproduce the linker error by -DCMAKE_CXX_FLAGS:str="-fvisibility=hidden" when calling cmake.
My suggestion is to check flags -fvisibility=hidden and -fvisibility-inlines-hidden, but I don't know their equivalent in MSVC. Thanks.

**Comment by jacques-menu** [comment]
Hello school510587,

I’ve added EXP to all ‘operator<<‘ occurrences in src/lilypond/*.h, and pushed that to the lilypond branch (that’s where I contribute my work, Dom does the merging with the dev branch) some days ago.

JM

**Comment by school510587** [comment]
Hi @dfober and @jacques-menu,

I checked out lilypond branch, and compilation completed with -fvisibility=hidden.
Before closing this issue, could you add such lines into CMakeLists.txt:

check_cxx_compiler_flag (-fvisibility=hidden FVISIBILITY_HIDDEN)
if(${FVISIBILITY_HIDDEN})
    set(CMAKE_CXX_FLAGS "-fvisibility=hidden ${CMAKE_CXX_FLAGS}")
endif()

Note that it is not inside any other if-else-endif block, because it does not depend on the OS.
I remember @dfober asked me to trace the latest version from dev branch.
So, if you don't feel trouble, please merge commit 83bb34 and the above code into dev branch. Thanks!

**Comment by dfober** [comment]
Sorry, I'm really busy up to the end of the month and I prefer to carefully check on all platforms (and especially with MSVC).  I'll do that in February.

**Comment by school510587** [comment]
Hi @dfober,

Thanks for quick reply. I have completed compilation of commit 131ceb locally.
Sorry, I generated MinGW makefiles by
  cmake build -G "MinGW Makefiles"
and ran it directly by mingw32-make, because I was not familiar to MSYS environment.
It seems MinGW g++ treats all declarations without explicit visibility specification as visibility=hidden. So, I think that setting -fvisibility=hidden will cause compilation failure if other EXP declaration is forgotten at text time. However, it's also ok if you think changing visibility in CMakeLists.txt is not necessary.

**Comment by dfober** [comment]
Exporting explicitly the functions that need to be exported is also a way to ensure a correct interface declaration. In addition, the -fvisibility=hidden is compiler dependant and will not work with MSVC. Thus if the current solution works, we'll leave the CMakelist.txt file as is.

**Comment by school510587** [comment]
Closed because 131ce fixed this problem.
