### ISSUE TITLE
Does this library generate music from MusicXML?

### ISSUE THREAD

**Issue by gonghuiyuan516** [grame-cncm/libmusicxml#33]
你好，我英语水平不好。请教个问题，这个库可以根据MusicXML 生成曲谱么
Hello, my English is poor.Question: can this library generate music from MusicXML

**Comment by dfober** [comment]
Hi,
The purpose of the library is to build a memory representation of MusicXML formatted data and to provide high level functions to manipulate this representation (for example, converters to other music representation formats). The library does not generate music in itself. It's actually a resource for application developers.
--
Dominique

**Comment by jacques-menu** [comment]
Hello,

You can actually generate music if you first convert MusicXML to LilyPond code, and then use LilyPond to obtain a score and music from it. But that’s no direct route, of course, and it implies the use of another tool.

More about this on the architecture overview at https://github.com/grame-cncm/libmusicxml/blob/lilypond/doc/lilypond/libmusicxmlArchitecture.pdf .

JM
