### ISSUE TITLE
XML Standard Comments are not parsed

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/libmusicxml#39]
Comment of type `<!-- This is a comment -->` (standard XML comment format) are not parsed and lead to syntax error.

I believe this has something to do with the Bison parser definition.

See attached example.

[A01-SOURCEQueen1.xml.zip](https://github.com/grame-cncm/libmusicxml/files/4165866/A01-SOURCEQueen1.xml.zip)

**Comment by dfober** [comment]
fixed (the parser was not expecting a comment between DOCTYPE and first element :-)

**Comment by arshiacont** [comment]
wonderful!!!
