### ISSUE TITLE
xml2guido crash

### ISSUE THREAD

**Issue by dfober** [grame-cncm/libmusicxml#40]
conversion crashes with the following file:
[PartGroups_LOOP.xml.zip](https://github.com/grame-cncm/libmusicxml/files/4680378/PartGroups_LOOP.xml.zip)

**Comment by arshiacont** [comment]
The MusicXML is weird! There's a Wedge start _without_ a stop and I assumed there is always one (which there should otherwise the XML is not valid).
I can certainly fix that by for example ignoring them (I do this anyway  for Slurs who start on one voice and finish on another in XML as they can not be handled in Guido).
But I'm curious if you can send me the unedited version if it also crashes.

**Comment by dfober** [comment]
I don't know where this file comes from. If it's not too complicated, it would be good to avoid crashes as much as possible (there's nothing like a very robust code).

**Comment by jacques-menu** [comment]
Hello Arshia,

PartGroups_LOOP.xml looks like the name of file produced by ‘xml2ly -loop PartGroups.xml’, which I’ve been testing some time ago. 
Did you find it in the git repository?

JM

**Comment by arshiacont** [comment]
@jacques-menu It comes from Dominique and I assume it comes from the repository.

I will fix this and other similar issues and send a PR (I have lots of improvements elsewhere for xml2guido and it's time anyway).

Do we have a specific Policy in LibMusicXML for throwing Exceptions for example in case of error?

**Comment by dfober** [comment]
No, there isn't. But we could define one.

**Comment by arshiacont** [comment]
ok.. this is now fixed on my local copy and will be sent as a PR (for xml2guido 3.1 including other features and fixes).

Ideally a convertor should never crash and should send errors, either as a library or application. I am not that much familiar with C++ Exceptions and their behaviour in libraries. But this is what I'd do in Swift and similar, starting to define an Enum like structure with common Error Types.

**Comment by arshiacont** [comment]
@dfober This is now PullRequest #41 including this fix and lots of others. It is in _production_ on our services and tested (on OSX/iOS). Let me know if there's any problem.

**Comment by jacques-menu** [comment]
Hello Arshia,

FYI, here is what I’ve just done for the lilypond branch for what it’s worth, avoiding an enum:

https://github.com/grame-cncm/libmusicxml/blob/lilypond/src/utilities/exceptions.h <https://github.com/grame-cncm/libmusicxml/blob/lilypond/src/utilities/exceptions.h>

https://github.com/grame-cncm/libmusicxml/blob/lilypond/src/utilities/messagesHandling.cpp <https://github.com/grame-cncm/libmusicxml/blob/lilypond/src/utilities/messagesHandling.cpp>

https://github.com/grame-cncm/libmusicxml/blob/lilypond/samples/xml2ly.cpp <https://github.com/grame-cncm/libmusicxml/blob/lilypond/samples/xml2ly.cpp>

https://github.com/grame-cncm/libmusicxml/blob/lilypond/src/lilypond/musicxml2lilypond.cpp <https://github.com/grame-cncm/libmusicxml/blob/lilypond/src/lilypond/musicxml2lilypond.cpp>

JM
