### ISSUE TITLE
How to use libmusicxml2.a file?

### ISSUE THREAD

**Issue by SaqG** [grame-cncm/libmusicxml#42]
I used cmake to generate the libmusicxml2.a file, but I did not see the Headers file. It cannot be used when importing into the project. What should I do?

**Comment by dfober** [comment]
The header file is in src/interface/libmusicxml.h
Is it what you're looking for?

**Comment by SaqG** [comment]
@dfober Thanks, I want to add it to my IOS app and use it to display music scores.

**Comment by dfober** [comment]
Fine! Do you already have a rendering engine for the music scores?

**Comment by SaqG** [comment]
@dfober No, I don't. I'm going to implement it with libmusicxml. Can it do that？

**Comment by dfober** [comment]
You should have a look at the [guido engine](https://github.com/grame-cncm/guidolib), the library embeds a converter from musicxml to the [guido format](https://guidodoc.grame.fr/), thus that should be quite straightforward..

**Comment by SaqG** [comment]
Yes, I'm learning about it, but I can't generate a library that IOS can use, because I'm new to cmake. Can you help me?

**Comment by dfober** [comment]
the makefile has a target `ios`. All you have to do is:
~~~~~~~~
$ make ios
~~~~~~~~
(from the build folder)

**Comment by SaqG** [comment]
I did that, but I had problems after "make ios"

The following build commands failed:
	CompileC iosdir/guidolib.build/Release-iphoneos/GUIDOEngine.build/Objects-normal/arm64/PianoRollTrajectory.o /Users/saq/Desktop/guidolib-dev/src/engine/alt-rep/PianoRollTrajectory.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [ios] Error 65
