### ISSUE TITLE
About xml2guido to gmn can’t show pedal

### ISSUE THREAD

**Issue by zhwei8090** [grame-cncm/libmusicxml#45]
Found that there is no way to display the pedals on the pavement, the library I use is the latest

**Comment by arshiacont** [comment]
I have this implemented already.. will create a PR soon.

**Comment by zhwei8090** [comment]
Haven't updated in a while

**Comment by arshiacont** [comment]
@zhwei8090 pedal support is now integrated `dev` branch since PR #46 
You can close this issue at your ease.

**Comment by zhwei8090** [comment]
@arshiacont I admire you very much, very excellent
