### ISSUE TITLE
CMakeLists.txt: Correct target name

### ISSUE THREAD

**Issue by school510587** [grame-cncm/libmusicxml#47]
I use cmake and MinGW to build libmusicxml. I obtain liblibmusicxml.dll, which seens not to be an expected output name. Change this line:

```
set(target libmusicxml)
```

to

```
set(target musicxml)
```

will solve this issue. Thanks.

**Comment by dfober** [comment]
done. Could you check (I don't use MINGW) and close this issue if it works.

**Comment by school510587** [comment]
Hi @dfober,

The variable MSYS is not set in the MinGW environment. The following must work:

```
  if(MINGW)
	set(target musicxml)
  else()
	set(target libmusicxml)
  endif()
```

**Comment by school510587** [comment]
OK, it works. Thanks.
