### ISSUE TITLE
Or the octave problem, I found that I can't get around it

### ISSUE THREAD

**Issue by zhwei8090** [grame-cncm/libmusicxml#51]
When the octave label appears at the last position of the measure, the sound at the first position of the next measure will inevitably be affected. Through analysis, there should be a problem when converting xml to gmn
exported xml：
[42_3_finale.xml.zip](https://github.com/grame-cncm/libmusicxml/files/8402010/42_3_finale.xml.zip)
In finale it is like this：
![image](https://user-images.githubusercontent.com/27411051/161371480-0b1689a9-6269-4dd4-9246-68544287eb28.png)
But after converting to gmn, it's not right, moved down an octave：
![image](https://user-images.githubusercontent.com/27411051/161371508-c63dd2a8-dfcb-4742-8206-79dcfc14cfda.png)

```
{[ \staff<1> \set<autoHideTiedAccidentals="on"> \auto<autoInstrPos="on"> \instr<"钢琴"> \accol<id=0, range="1-2"> \barFormat<style= "system", range="1-2"> 
   (* meas. 1 *)  \clef<"g2"> \key<0> \meter<"4/4", autoBarlines="off", autoMeasuresNum="system"> \oct<1> \stemsDown \beamsOff b2/2 \stemsDown \beamsOff b2/2 \oct<0> \bar<measNum=2> 
   (* meas. 2 *)  \stemsAuto \beamsOff b0/1 ]
 , 
[ \staff<2> \set<autoHideTiedAccidentals="on"> \barFormat<style= "system", range="2"> 
   (* meas. 1 *)  \staffFormat<distance=13> \clef<"f4"> \key<0> \meter<"4/4", autoBarlines="off", autoMeasuresNum="system"> _/1 \bar<measNum=2> 
   (* meas. 2 *)  _/1 ]
  }

```

**Comment by zhwei8090** [comment]
It has been solved, create a pr, please take a look, thank you

**Comment by arshiacont** [comment]
@zhwei8090 where did you create the PR? I can't see it here

**Comment by zhwei8090** [comment]
@arshiacont It has been submitted, please check it, thank you

**Comment by zhwei8090** [comment]
I have no problem with the initial test here, you can verify it again

**Comment by arshiacont** [comment]
Thank you @zhwei8090 ! and sorry I forgot to correctly initialize the variable... 👍
