### ISSUE TITLE
xcode 14 make ios error

### ISSUE THREAD

**Issue by BuildFaild** [grame-cncm/libmusicxml#60]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/12441358/192475756-cece6166-7dbc-4603-a31e-17dfa7794393.png">

**Comment by BuildFaild** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/12441358/192463262-7cc2f1f0-b0b7-474d-9ed5-c85c4b1a45ec.png">

**Comment by jacques-menu** [comment]
Hello,

Did you install the full Xcode on your machine? Building is fine here, on a Mac Mini with Mac OS Monterey 12.6.

JM

**Comment by dfober** [comment]
This is a recurring problem with ios: the CMAKE_OSX_SYSROOT can change its name with the version of xcode but actually it seems that this variable is not necessary. I've pushed a fix on the dev branch. Could test it?

**Comment by jacques-menu** [comment]
Pulled and re-built, OK here.

JM
