### ISSUE TITLE
MusicXML 4.0 Support

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/libmusicxml#63]
It seems to me that LibMusicXML is not on MusicXML 4.0 DTDs or I am making a mistake?!

**Comment by dfober** [comment]
That's right. The latest supported version is 3.1

**Comment by dfober** [comment]
It looks like version 4.0 doesn't introduces new elements. As far as I can see, the main changes concern documentation and types. Can you confirm ? And if you have any files encoded in version 4, could you send them to me?

**Comment by arshiacont** [comment]
I actually came across an export from Finale that had a the following element crashing LibMusicXML:

```
<sound>
        <swing>
          <straight/>
        </swing>
</sound>
```

which makes me think that there are some new elements that LibMusicXML doesn't like. 

Here is one:
[testMusicXML4.xml.zip](https://github.com/grame-cncm/libmusicxml/files/13438190/testMusicXML4.xml.zip)

**Comment by dfober** [comment]
The file works on my side (using xmlread tool), it's also converted to gmn without problem. Now it makes use of the latest version but the src has not been affected by the update to v4.

**Comment by arshiacont** [comment]
Interesting! So it's something on my branch.. I'll do a quick check and will update here or close accordingly! Thanks for checking it up.
